version: '2'

services:
  web:
    build: .
    image: codingphase
    command: bash -c 'npm install && npm run watch'
    working_dir: /app/local
    volumes:
      - '.:/app/local'

  app:
    build: .
    image: codingphase
    command: 'amber watch'
    working_dir: /app/local
    environment:
      DATABASE_URL: mysql://admin:password@db:3306/codingphase_development
      SMTP_URL: mail:1025
    ports:
      - '3000:3000'
    links:
      - db
      - mail
    volumes:
      - '.:/app/local'

  migrate:
    build: .
    image: codingphase
    command: bash -c 'while ! nc -q 1 db 3306 </dev/null; do sleep 1; done && amber db migrate seed'
    working_dir: /app/local
    environment:
      DATABASE_URL: mysql://admin:password@db:3306/codingphase_development
    volumes:
      - '.:/app/local'
    links:
      - db

  mail:
    image: drujensen/mailcatcher:latest
    ports:
      - '1080:1080'

  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: codingphase_development
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - 'db:/var/lib/mysql'

volumes:
  db:
