secret_key_base: R91pMZ5uJX-ZmWFwmx9A9i46gmUAE8AkdtNXdMPs21A
port: (ENV["PORT"] || 3000).to_i
name: codingphase
log: "::Logger.new(STDOUT)"
log_level: "::Logger::INFO"
color: false
host: 0.0.0.0
port_reuse: false
process_count: (ENV["AMBER_PROCESS_COUNT"]? || 1).to_i
ssl_key_file:
ssl_cert_file:
redis_url: "redis://localhost:6379"
session:
  key: amber.session
  store: :signed_cookie
  expires: 0
secrets:
  description: Store your development secrets credentials and settings here.
  database: mysql://root@localhost:3306/codingphase_development
